/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.qtech.chk.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EqReverseCtrlInfoRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 7892185434689128003L;


    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EqReverseCtrlInfoRecord\",\"namespace\":\"com.qtech.chk.avro\",\"fields\":[{\"name\":\"simId\",\"type\":\"string\"},{\"name\":\"moduleId\",\"type\":[\"string\",\"null\"],\"default\":\"defaultString\"},{\"name\":\"chkDt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"description\",\"type\":[\"string\",\"null\"],\"default\":\"defaultString\"}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    static {
        MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    }

    private static final BinaryMessageEncoder<EqReverseCtrlInfoRecord> ENCODER =
            new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<EqReverseCtrlInfoRecord> DECODER =
            new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<EqReverseCtrlInfoRecord> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<EqReverseCtrlInfoRecord> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<EqReverseCtrlInfoRecord> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this EqReverseCtrlInfoRecord to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a EqReverseCtrlInfoRecord from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a EqReverseCtrlInfoRecord instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static EqReverseCtrlInfoRecord fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private java.lang.CharSequence simId;
    private java.lang.CharSequence moduleId;
    private java.time.Instant chkDt;
    private int code;
    private java.lang.CharSequence description;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public EqReverseCtrlInfoRecord() {
    }

    /**
     * All-args constructor.
     * @param simId The new value for simId
     * @param moduleId The new value for moduleId
     * @param chkDt The new value for chkDt
     * @param code The new value for code
     * @param description The new value for description
     */
    public EqReverseCtrlInfoRecord(java.lang.CharSequence simId, java.lang.CharSequence moduleId, java.time.Instant chkDt, java.lang.Integer code, java.lang.CharSequence description) {
        this.simId = simId;
        this.moduleId = moduleId;
        this.chkDt = chkDt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
        this.code = code;
        this.description = description;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return simId;
            case 1:
                return moduleId;
            case 2:
                return chkDt;
            case 3:
                return code;
            case 4:
                return description;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    private static final org.apache.avro.Conversion<?>[] conversions =
            new org.apache.avro.Conversion<?>[]{
                    null,
                    null,
                    new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
                    null,
                    null,
                    null
            };

    @Override
    public org.apache.avro.Conversion<?> getConversion(int field) {
        return conversions[field];
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                simId = (java.lang.CharSequence) value$;
                break;
            case 1:
                moduleId = (java.lang.CharSequence) value$;
                break;
            case 2:
                chkDt = (java.time.Instant) value$;
                break;
            case 3:
                code = (java.lang.Integer) value$;
                break;
            case 4:
                description = (java.lang.CharSequence) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'simId' field.
     * @return The value of the 'simId' field.
     */
    public java.lang.CharSequence getSimId() {
        return simId;
    }


    /**
     * Sets the value of the 'simId' field.
     * @param value the value to set.
     */
    public void setSimId(java.lang.CharSequence value) {
        this.simId = value;
    }

    /**
     * Gets the value of the 'moduleId' field.
     * @return The value of the 'moduleId' field.
     */
    public java.lang.CharSequence getModuleId() {
        return moduleId;
    }


    /**
     * Sets the value of the 'moduleId' field.
     * @param value the value to set.
     */
    public void setModuleId(java.lang.CharSequence value) {
        this.moduleId = value;
    }

    /**
     * Gets the value of the 'chkDt' field.
     * @return The value of the 'chkDt' field.
     */
    public java.time.Instant getChkDt() {
        return chkDt;
    }


    /**
     * Sets the value of the 'chkDt' field.
     * @param value the value to set.
     */
    public void setChkDt(java.time.Instant value) {
        this.chkDt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    }

    /**
     * Gets the value of the 'code' field.
     * @return The value of the 'code' field.
     */
    public int getCode() {
        return code;
    }


    /**
     * Sets the value of the 'code' field.
     * @param value the value to set.
     */
    public void setCode(int value) {
        this.code = value;
    }

    /**
     * Gets the value of the 'description' field.
     * @return The value of the 'description' field.
     */
    public java.lang.CharSequence getDescription() {
        return description;
    }


    /**
     * Sets the value of the 'description' field.
     * @param value the value to set.
     */
    public void setDescription(java.lang.CharSequence value) {
        this.description = value;
    }

    /**
     * Creates a new EqReverseCtrlInfoRecord RecordBuilder.
     * @return A new EqReverseCtrlInfoRecord RecordBuilder
     */
    public static com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder newBuilder() {
        return new com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder();
    }

    /**
     * Creates a new EqReverseCtrlInfoRecord RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new EqReverseCtrlInfoRecord RecordBuilder
     */
    public static com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder newBuilder(com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder other) {
        if (other == null) {
            return new com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder();
        } else {
            return new com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder(other);
        }
    }

    /**
     * Creates a new EqReverseCtrlInfoRecord RecordBuilder by copying an existing EqReverseCtrlInfoRecord instance.
     * @param other The existing instance to copy.
     * @return A new EqReverseCtrlInfoRecord RecordBuilder
     */
    public static com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder newBuilder(com.qtech.chk.avro.EqReverseCtrlInfoRecord other) {
        if (other == null) {
            return new com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder();
        } else {
            return new com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder(other);
        }
    }

    /**
     * RecordBuilder for EqReverseCtrlInfoRecord instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EqReverseCtrlInfoRecord>
            implements org.apache.avro.data.RecordBuilder<EqReverseCtrlInfoRecord> {

        private java.lang.CharSequence simId;
        private java.lang.CharSequence moduleId;
        private java.time.Instant chkDt;
        private int code;
        private java.lang.CharSequence description;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.simId)) {
                this.simId = data().deepCopy(fields()[0].schema(), other.simId);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.moduleId)) {
                this.moduleId = data().deepCopy(fields()[1].schema(), other.moduleId);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.chkDt)) {
                this.chkDt = data().deepCopy(fields()[2].schema(), other.chkDt);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.code)) {
                this.code = data().deepCopy(fields()[3].schema(), other.code);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
            if (isValidValue(fields()[4], other.description)) {
                this.description = data().deepCopy(fields()[4].schema(), other.description);
                fieldSetFlags()[4] = other.fieldSetFlags()[4];
            }
        }

        /**
         * Creates a Builder by copying an existing EqReverseCtrlInfoRecord instance
         * @param other The existing instance to copy.
         */
        private Builder(com.qtech.chk.avro.EqReverseCtrlInfoRecord other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.simId)) {
                this.simId = data().deepCopy(fields()[0].schema(), other.simId);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.moduleId)) {
                this.moduleId = data().deepCopy(fields()[1].schema(), other.moduleId);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.chkDt)) {
                this.chkDt = data().deepCopy(fields()[2].schema(), other.chkDt);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.code)) {
                this.code = data().deepCopy(fields()[3].schema(), other.code);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.description)) {
                this.description = data().deepCopy(fields()[4].schema(), other.description);
                fieldSetFlags()[4] = true;
            }
        }

        /**
         * Gets the value of the 'simId' field.
         * @return The value.
         */
        public java.lang.CharSequence getSimId() {
            return simId;
        }


        /**
         * Sets the value of the 'simId' field.
         * @param value The value of 'simId'.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder setSimId(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.simId = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'simId' field has been set.
         * @return True if the 'simId' field has been set, false otherwise.
         */
        public boolean hasSimId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'simId' field.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder clearSimId() {
            simId = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'moduleId' field.
         * @return The value.
         */
        public java.lang.CharSequence getModuleId() {
            return moduleId;
        }


        /**
         * Sets the value of the 'moduleId' field.
         * @param value The value of 'moduleId'.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder setModuleId(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.moduleId = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'moduleId' field has been set.
         * @return True if the 'moduleId' field has been set, false otherwise.
         */
        public boolean hasModuleId() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'moduleId' field.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder clearModuleId() {
            moduleId = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'chkDt' field.
         * @return The value.
         */
        public java.time.Instant getChkDt() {
            return chkDt;
        }


        /**
         * Sets the value of the 'chkDt' field.
         * @param value The value of 'chkDt'.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder setChkDt(java.time.Instant value) {
            validate(fields()[2], value);
            this.chkDt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'chkDt' field has been set.
         * @return True if the 'chkDt' field has been set, false otherwise.
         */
        public boolean hasChkDt() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'chkDt' field.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder clearChkDt() {
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'code' field.
         * @return The value.
         */
        public int getCode() {
            return code;
        }


        /**
         * Sets the value of the 'code' field.
         * @param value The value of 'code'.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder setCode(int value) {
            validate(fields()[3], value);
            this.code = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'code' field has been set.
         * @return True if the 'code' field has been set, false otherwise.
         */
        public boolean hasCode() {
            return fieldSetFlags()[3];
        }


        /**
         * Clears the value of the 'code' field.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder clearCode() {
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'description' field.
         * @return The value.
         */
        public java.lang.CharSequence getDescription() {
            return description;
        }


        /**
         * Sets the value of the 'description' field.
         * @param value The value of 'description'.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder setDescription(java.lang.CharSequence value) {
            validate(fields()[4], value);
            this.description = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'description' field has been set.
         * @return True if the 'description' field has been set, false otherwise.
         */
        public boolean hasDescription() {
            return fieldSetFlags()[4];
        }


        /**
         * Clears the value of the 'description' field.
         * @return This builder.
         */
        public com.qtech.chk.avro.EqReverseCtrlInfoRecord.Builder clearDescription() {
            description = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public EqReverseCtrlInfoRecord build() {
            try {
                EqReverseCtrlInfoRecord record = new EqReverseCtrlInfoRecord();
                record.simId = fieldSetFlags()[0] ? this.simId : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.moduleId = fieldSetFlags()[1] ? this.moduleId : (java.lang.CharSequence) defaultValue(fields()[1]);
                record.chkDt = fieldSetFlags()[2] ? this.chkDt : (java.time.Instant) defaultValue(fields()[2]);
                record.code = fieldSetFlags()[3] ? this.code : (java.lang.Integer) defaultValue(fields()[3]);
                record.description = fieldSetFlags()[4] ? this.description : (java.lang.CharSequence) defaultValue(fields()[4]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<EqReverseCtrlInfoRecord>
            WRITER$ = (org.apache.avro.io.DatumWriter<EqReverseCtrlInfoRecord>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<EqReverseCtrlInfoRecord>
            READER$ = (org.apache.avro.io.DatumReader<EqReverseCtrlInfoRecord>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

}










