/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.im.qtech.common.avro.record;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class EqpReversePOJORecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -2203551944888749256L;


    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EqpReversePOJORecord\",\"namespace\":\"com.im.qtech.common.avro.record\",\"fields\":[{\"name\":\"simId\",\"type\":\"string\"},{\"name\":\"source\",\"type\":\"string\"},{\"name\":\"module\",\"type\":[\"string\",\"null\"],\"default\":\"defaultString\"},{\"name\":\"chkDt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"passed\",\"type\":[\"boolean\"],\"default\":true},{\"name\":\"label\",\"type\":[\"string\",\"null\"],\"default\":\"defaultString\"},{\"name\":\"reason\",\"type\":[\"string\",\"null\"],\"default\":\"defaultString\"},{\"name\":\"description\",\"type\":[\"string\",\"null\"],\"default\":\"defaultString\"}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    static {
        MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    }

    private static final BinaryMessageEncoder<EqpReversePOJORecord> ENCODER =
            new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<EqpReversePOJORecord> DECODER =
            new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<EqpReversePOJORecord> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<EqpReversePOJORecord> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<EqpReversePOJORecord> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this EqpReversePOJORecord to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a EqpReversePOJORecord from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a EqpReversePOJORecord instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static EqpReversePOJORecord fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private java.lang.CharSequence simId;
    private java.lang.CharSequence source;
    private java.lang.CharSequence module;
    private java.time.Instant chkDt;
    private int code;
    private java.lang.Object passed;
    private java.lang.CharSequence label;
    private java.lang.CharSequence reason;
    private java.lang.CharSequence description;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public EqpReversePOJORecord() {
    }

    /**
     * All-args constructor.
     * @param simId The new value for simId
     * @param source The new value for source
     * @param module The new value for module
     * @param chkDt The new value for chkDt
     * @param code The new value for code
     * @param passed The new value for passed
     * @param label The new value for label
     * @param reason The new value for reason
     * @param description The new value for description
     */
    public EqpReversePOJORecord(java.lang.CharSequence simId, java.lang.CharSequence source, java.lang.CharSequence module, java.time.Instant chkDt, java.lang.Integer code, java.lang.Object passed, java.lang.CharSequence label, java.lang.CharSequence reason, java.lang.CharSequence description) {
        this.simId = simId;
        this.source = source;
        this.module = module;
        this.chkDt = chkDt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
        this.code = code;
        this.passed = passed;
        this.label = label;
        this.reason = reason;
        this.description = description;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return simId;
            case 1:
                return source;
            case 2:
                return module;
            case 3:
                return chkDt;
            case 4:
                return code;
            case 5:
                return passed;
            case 6:
                return label;
            case 7:
                return reason;
            case 8:
                return description;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    private static final org.apache.avro.Conversion<?>[] conversions =
            new org.apache.avro.Conversion<?>[]{
                    null,
                    null,
                    null,
                    new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
            };

    @Override
    public org.apache.avro.Conversion<?> getConversion(int field) {
        return conversions[field];
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                simId = (java.lang.CharSequence) value$;
                break;
            case 1:
                source = (java.lang.CharSequence) value$;
                break;
            case 2:
                module = (java.lang.CharSequence) value$;
                break;
            case 3:
                chkDt = (java.time.Instant) value$;
                break;
            case 4:
                code = (java.lang.Integer) value$;
                break;
            case 5:
                passed = value$;
                break;
            case 6:
                label = (java.lang.CharSequence) value$;
                break;
            case 7:
                reason = (java.lang.CharSequence) value$;
                break;
            case 8:
                description = (java.lang.CharSequence) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'simId' field.
     * @return The value of the 'simId' field.
     */
    public java.lang.CharSequence getSimId() {
        return simId;
    }


    /**
     * Sets the value of the 'simId' field.
     * @param value the value to set.
     */
    public void setSimId(java.lang.CharSequence value) {
        this.simId = value;
    }

    /**
     * Gets the value of the 'source' field.
     * @return The value of the 'source' field.
     */
    public java.lang.CharSequence getSource() {
        return source;
    }


    /**
     * Sets the value of the 'source' field.
     * @param value the value to set.
     */
    public void setSource(java.lang.CharSequence value) {
        this.source = value;
    }

    /**
     * Gets the value of the 'module' field.
     * @return The value of the 'module' field.
     */
    public java.lang.CharSequence getModule() {
        return module;
    }


    /**
     * Sets the value of the 'module' field.
     * @param value the value to set.
     */
    public void setModule(java.lang.CharSequence value) {
        this.module = value;
    }

    /**
     * Gets the value of the 'chkDt' field.
     * @return The value of the 'chkDt' field.
     */
    public java.time.Instant getChkDt() {
        return chkDt;
    }


    /**
     * Sets the value of the 'chkDt' field.
     * @param value the value to set.
     */
    public void setChkDt(java.time.Instant value) {
        this.chkDt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    }

    /**
     * Gets the value of the 'code' field.
     * @return The value of the 'code' field.
     */
    public int getCode() {
        return code;
    }


    /**
     * Sets the value of the 'code' field.
     * @param value the value to set.
     */
    public void setCode(int value) {
        this.code = value;
    }

    /**
     * Gets the value of the 'passed' field.
     * @return The value of the 'passed' field.
     */
    public java.lang.Object getPassed() {
        return passed;
    }


    /**
     * Sets the value of the 'passed' field.
     * @param value the value to set.
     */
    public void setPassed(java.lang.Object value) {
        this.passed = value;
    }

    /**
     * Gets the value of the 'label' field.
     * @return The value of the 'label' field.
     */
    public java.lang.CharSequence getLabel() {
        return label;
    }


    /**
     * Sets the value of the 'label' field.
     * @param value the value to set.
     */
    public void setLabel(java.lang.CharSequence value) {
        this.label = value;
    }

    /**
     * Gets the value of the 'reason' field.
     * @return The value of the 'reason' field.
     */
    public java.lang.CharSequence getReason() {
        return reason;
    }


    /**
     * Sets the value of the 'reason' field.
     * @param value the value to set.
     */
    public void setReason(java.lang.CharSequence value) {
        this.reason = value;
    }

    /**
     * Gets the value of the 'description' field.
     * @return The value of the 'description' field.
     */
    public java.lang.CharSequence getDescription() {
        return description;
    }


    /**
     * Sets the value of the 'description' field.
     * @param value the value to set.
     */
    public void setDescription(java.lang.CharSequence value) {
        this.description = value;
    }

    /**
     * Creates a new EqpReversePOJORecord RecordBuilder.
     * @return A new EqpReversePOJORecord RecordBuilder
     */
    public static com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder newBuilder() {
        return new com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder();
    }

    /**
     * Creates a new EqpReversePOJORecord RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new EqpReversePOJORecord RecordBuilder
     */
    public static com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder newBuilder(com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder other) {
        if (other == null) {
            return new com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder();
        } else {
            return new com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder(other);
        }
    }

    /**
     * Creates a new EqpReversePOJORecord RecordBuilder by copying an existing EqpReversePOJORecord instance.
     * @param other The existing instance to copy.
     * @return A new EqpReversePOJORecord RecordBuilder
     */
    public static com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder newBuilder(com.im.qtech.common.avro.record.EqpReversePOJORecord other) {
        if (other == null) {
            return new com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder();
        } else {
            return new com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder(other);
        }
    }

    /**
     * RecordBuilder for EqpReversePOJORecord instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EqpReversePOJORecord>
            implements org.apache.avro.data.RecordBuilder<EqpReversePOJORecord> {

        private java.lang.CharSequence simId;
        private java.lang.CharSequence source;
        private java.lang.CharSequence module;
        private java.time.Instant chkDt;
        private int code;
        private java.lang.Object passed;
        private java.lang.CharSequence label;
        private java.lang.CharSequence reason;
        private java.lang.CharSequence description;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.simId)) {
                this.simId = data().deepCopy(fields()[0].schema(), other.simId);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.source)) {
                this.source = data().deepCopy(fields()[1].schema(), other.source);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.module)) {
                this.module = data().deepCopy(fields()[2].schema(), other.module);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.chkDt)) {
                this.chkDt = data().deepCopy(fields()[3].schema(), other.chkDt);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
            if (isValidValue(fields()[4], other.code)) {
                this.code = data().deepCopy(fields()[4].schema(), other.code);
                fieldSetFlags()[4] = other.fieldSetFlags()[4];
            }
            if (isValidValue(fields()[5], other.passed)) {
                this.passed = data().deepCopy(fields()[5].schema(), other.passed);
                fieldSetFlags()[5] = other.fieldSetFlags()[5];
            }
            if (isValidValue(fields()[6], other.label)) {
                this.label = data().deepCopy(fields()[6].schema(), other.label);
                fieldSetFlags()[6] = other.fieldSetFlags()[6];
            }
            if (isValidValue(fields()[7], other.reason)) {
                this.reason = data().deepCopy(fields()[7].schema(), other.reason);
                fieldSetFlags()[7] = other.fieldSetFlags()[7];
            }
            if (isValidValue(fields()[8], other.description)) {
                this.description = data().deepCopy(fields()[8].schema(), other.description);
                fieldSetFlags()[8] = other.fieldSetFlags()[8];
            }
        }

        /**
         * Creates a Builder by copying an existing EqpReversePOJORecord instance
         * @param other The existing instance to copy.
         */
        private Builder(com.im.qtech.common.avro.record.EqpReversePOJORecord other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.simId)) {
                this.simId = data().deepCopy(fields()[0].schema(), other.simId);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.source)) {
                this.source = data().deepCopy(fields()[1].schema(), other.source);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.module)) {
                this.module = data().deepCopy(fields()[2].schema(), other.module);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.chkDt)) {
                this.chkDt = data().deepCopy(fields()[3].schema(), other.chkDt);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.code)) {
                this.code = data().deepCopy(fields()[4].schema(), other.code);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.passed)) {
                this.passed = data().deepCopy(fields()[5].schema(), other.passed);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.label)) {
                this.label = data().deepCopy(fields()[6].schema(), other.label);
                fieldSetFlags()[6] = true;
            }
            if (isValidValue(fields()[7], other.reason)) {
                this.reason = data().deepCopy(fields()[7].schema(), other.reason);
                fieldSetFlags()[7] = true;
            }
            if (isValidValue(fields()[8], other.description)) {
                this.description = data().deepCopy(fields()[8].schema(), other.description);
                fieldSetFlags()[8] = true;
            }
        }

        /**
         * Gets the value of the 'simId' field.
         * @return The value.
         */
        public java.lang.CharSequence getSimId() {
            return simId;
        }


        /**
         * Sets the value of the 'simId' field.
         * @param value The value of 'simId'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setSimId(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.simId = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'simId' field has been set.
         * @return True if the 'simId' field has been set, false otherwise.
         */
        public boolean hasSimId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'simId' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearSimId() {
            simId = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'source' field.
         * @return The value.
         */
        public java.lang.CharSequence getSource() {
            return source;
        }


        /**
         * Sets the value of the 'source' field.
         * @param value The value of 'source'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setSource(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.source = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'source' field has been set.
         * @return True if the 'source' field has been set, false otherwise.
         */
        public boolean hasSource() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'source' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearSource() {
            source = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'module' field.
         * @return The value.
         */
        public java.lang.CharSequence getModule() {
            return module;
        }


        /**
         * Sets the value of the 'module' field.
         * @param value The value of 'module'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setModule(java.lang.CharSequence value) {
            validate(fields()[2], value);
            this.module = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'module' field has been set.
         * @return True if the 'module' field has been set, false otherwise.
         */
        public boolean hasModule() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'module' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearModule() {
            module = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'chkDt' field.
         * @return The value.
         */
        public java.time.Instant getChkDt() {
            return chkDt;
        }


        /**
         * Sets the value of the 'chkDt' field.
         * @param value The value of 'chkDt'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setChkDt(java.time.Instant value) {
            validate(fields()[3], value);
            this.chkDt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'chkDt' field has been set.
         * @return True if the 'chkDt' field has been set, false otherwise.
         */
        public boolean hasChkDt() {
            return fieldSetFlags()[3];
        }


        /**
         * Clears the value of the 'chkDt' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearChkDt() {
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'code' field.
         * @return The value.
         */
        public int getCode() {
            return code;
        }


        /**
         * Sets the value of the 'code' field.
         * @param value The value of 'code'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setCode(int value) {
            validate(fields()[4], value);
            this.code = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'code' field has been set.
         * @return True if the 'code' field has been set, false otherwise.
         */
        public boolean hasCode() {
            return fieldSetFlags()[4];
        }


        /**
         * Clears the value of the 'code' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearCode() {
            fieldSetFlags()[4] = false;
            return this;
        }

        /**
         * Gets the value of the 'passed' field.
         * @return The value.
         */
        public java.lang.Object getPassed() {
            return passed;
        }


        /**
         * Sets the value of the 'passed' field.
         * @param value The value of 'passed'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setPassed(java.lang.Object value) {
            validate(fields()[5], value);
            this.passed = value;
            fieldSetFlags()[5] = true;
            return this;
        }

        /**
         * Checks whether the 'passed' field has been set.
         * @return True if the 'passed' field has been set, false otherwise.
         */
        public boolean hasPassed() {
            return fieldSetFlags()[5];
        }


        /**
         * Clears the value of the 'passed' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearPassed() {
            passed = null;
            fieldSetFlags()[5] = false;
            return this;
        }

        /**
         * Gets the value of the 'label' field.
         * @return The value.
         */
        public java.lang.CharSequence getLabel() {
            return label;
        }


        /**
         * Sets the value of the 'label' field.
         * @param value The value of 'label'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setLabel(java.lang.CharSequence value) {
            validate(fields()[6], value);
            this.label = value;
            fieldSetFlags()[6] = true;
            return this;
        }

        /**
         * Checks whether the 'label' field has been set.
         * @return True if the 'label' field has been set, false otherwise.
         */
        public boolean hasLabel() {
            return fieldSetFlags()[6];
        }


        /**
         * Clears the value of the 'label' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearLabel() {
            label = null;
            fieldSetFlags()[6] = false;
            return this;
        }

        /**
         * Gets the value of the 'reason' field.
         * @return The value.
         */
        public java.lang.CharSequence getReason() {
            return reason;
        }


        /**
         * Sets the value of the 'reason' field.
         * @param value The value of 'reason'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setReason(java.lang.CharSequence value) {
            validate(fields()[7], value);
            this.reason = value;
            fieldSetFlags()[7] = true;
            return this;
        }

        /**
         * Checks whether the 'reason' field has been set.
         * @return True if the 'reason' field has been set, false otherwise.
         */
        public boolean hasReason() {
            return fieldSetFlags()[7];
        }


        /**
         * Clears the value of the 'reason' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearReason() {
            reason = null;
            fieldSetFlags()[7] = false;
            return this;
        }

        /**
         * Gets the value of the 'description' field.
         * @return The value.
         */
        public java.lang.CharSequence getDescription() {
            return description;
        }


        /**
         * Sets the value of the 'description' field.
         * @param value The value of 'description'.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder setDescription(java.lang.CharSequence value) {
            validate(fields()[8], value);
            this.description = value;
            fieldSetFlags()[8] = true;
            return this;
        }

        /**
         * Checks whether the 'description' field has been set.
         * @return True if the 'description' field has been set, false otherwise.
         */
        public boolean hasDescription() {
            return fieldSetFlags()[8];
        }


        /**
         * Clears the value of the 'description' field.
         * @return This builder.
         */
        public com.im.qtech.common.avro.record.EqpReversePOJORecord.Builder clearDescription() {
            description = null;
            fieldSetFlags()[8] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public EqpReversePOJORecord build() {
            try {
                EqpReversePOJORecord record = new EqpReversePOJORecord();
                record.simId = fieldSetFlags()[0] ? this.simId : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.source = fieldSetFlags()[1] ? this.source : (java.lang.CharSequence) defaultValue(fields()[1]);
                record.module = fieldSetFlags()[2] ? this.module : (java.lang.CharSequence) defaultValue(fields()[2]);
                record.chkDt = fieldSetFlags()[3] ? this.chkDt : (java.time.Instant) defaultValue(fields()[3]);
                record.code = fieldSetFlags()[4] ? this.code : (java.lang.Integer) defaultValue(fields()[4]);
                record.passed = fieldSetFlags()[5] ? this.passed : defaultValue(fields()[5]);
                record.label = fieldSetFlags()[6] ? this.label : (java.lang.CharSequence) defaultValue(fields()[6]);
                record.reason = fieldSetFlags()[7] ? this.reason : (java.lang.CharSequence) defaultValue(fields()[7]);
                record.description = fieldSetFlags()[8] ? this.description : (java.lang.CharSequence) defaultValue(fields()[8]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<EqpReversePOJORecord>
            WRITER$ = (org.apache.avro.io.DatumWriter<EqpReversePOJORecord>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<EqpReversePOJORecord>
            READER$ = (org.apache.avro.io.DatumReader<EqpReversePOJORecord>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

}










