#
server:
  port: 8079
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 1000
      min-spare: 20
  servlet:
    context-path: /

spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    first:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://10.170.6.142:5432/imbiz
      username: biz
      password: FfZRT!FkF@K4pq9ZPpdC
    second:
      url: jdbc:mysql://10.170.6.40:32333/qtech_eq_dwd?useServerPrepStmts=false&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password:
    third:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//10.170.6.144:1521/qtechIm
      username: imBiz
      password: M5F5JkfnQ
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      connectTimeout: 30000
      socketTimeout: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

  data:
    redis:
      ## Redis服务器连接密码（默认为空）
      password: im@2024
      cluster:
        nodes:
          - 10.170.6.24:6379
          - 10.170.6.25:6379
          - 10.170.6.26:6379
          - 10.170.6.141:6379
          - 10.170.6.142:6379
          - 10.170.1.68:6379
        max-redirects: 3
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000
      timeout: 5000
      connect-timeout: 5000
      database: 0

  kafka:
    bootstrap-servers: 10.170.6.24:9092,10.170.6.25:9092,10.170.6.26:9092
    consumer:
      group-id: msg-persist-group
      auto-offset-reset: latest
    streams:
      application-id: im-msg-queue-persist

# MyBatis Plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.im.qtech.service.msg.entity, com.im.qtech.common.dto.*
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    use-generated-keys: false
    use-column-label: false

# corePoolSize不宜太大，2核CPU环境，最多允许4～5个活跃线程在抢CPU。
# queueCapacity 不能太大，控制住消息积压量，否则实时性急剧下降。
# RejectedExecutionHandler保持CallerRunsPolicy没问题（可以临时让生产者自己跑任务，保护系统稳定）。
# keepAliveSeconds可以低一点，加快释放空闲线程，节省内存。
thread-pool:
  virtual:
    permits: 5  # 限制并发数
    enabled: true
  important:
    corePoolSize: 2
    maxPoolSize: 3
    queueCapacity: 500
    keepAliveSeconds: 30
    threadNamePrefix: important-task-
  normal:
    corePoolSize: 1
    maxPoolSize: 2
    queueCapacity: 1000
    keepAliveSeconds: 30
    threadNamePrefix: normal-task-
  low:
    corePoolSize: 0
    maxPoolSize: 1
    queueCapacity: 100
    keepAliveSeconds: 30
    threadNamePrefix: low-task-
